### PR TITLE
add sql.sequel support

### PR DESCRIPTION
**Pull request by modosc**
this hacks in sequel support by pretending it's `sql.active_record` data.

i'm not sure it's the right solution but i'm hesitant to make any ui changes. i thought about altering the tab's title based on some flag but i don't know if people would potentially be using `sequel` _and_ `activerecord` at the same time. for now this probably is a good enough solution?

### CODE REVIEW

**Comment by gencer** [comment]
@modosc, I tried this branch and it did not worked. When I restart server, It generates errors. Had to disable meta_request gem.

stderr:
```
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/numeric/conversions.rb:104:in `to_s': SystemStackError: stack level too deep (Sequel::DatabaseConnectionError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `block in as_json'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `as_json'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `block in as_json'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:163:in `as_json'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/core_ext/object/json.rb:54:in `as_json'
```

And this is the **development.log**:
```
Could not log "sql.sequel" event. NoMethodError: undefined method `name' for #<Sequel::Postgres::Adapter:0x0055befd9e78e0> ["/usr/local/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/railties/log_subscriber.rb:45:in `block in sql'", "/usr/local/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/railties/log_subscriber.rb:44:in `map'", "/usr/local/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/railties/log_subscriber.rb:44:in `sql'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/subscriber.rb:99:in `finish'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/log_subscriber.rb:83:in `finish'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/fanout.rb:102:in `finish'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/fanout.rb:46:in `block in finish'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/fanout.rb:46:in `each'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/fanout.rb:46:in `finish'", "/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'", 
```

**Comment by modosc** [comment]
@gencer it works with the example repo you built - can you alter that repo so i can reproduce your issue?

**Comment by gencer** [comment]
@modosc, Nope. See, If you leave rails monitoring app enabled in development, this things can happen.

Monitoring tool I use was enabled at development and probing sequel. When I moved it to production only, it just works.

**Comment by modosc** [comment]
> Monitoring tool I use was enabled at development and probing sequel. When I moved it to production only, it just works.

what monitoring tool are you referring to?

**Comment by gencer** [comment]
> what monitoring tool are you referring to?

Skylight. When I add probe settings and tell that to probe sequel this happens.

**Pull request merged**
