### PR TITLE
Add Rails 7.0 to CI

### PR DESCRIPTION
**Pull request by leoarnold**
Closes #181

### CODE REVIEW

**Review by amrdruid — APPROVED** [review]

**Comment by amrdruid** [comment]
Thanks a million! I tested it throughly and I believe it's ready to go! Not an owner of the repo unfortunately. 

Hope we can get merge that instead of using my custom version

**Comment by amrdruid** [comment]
@dejan

**Comment by dejan** [comment]
Thanks @leoarnold and @amrdruid

**Comment by amrdruid** [comment]
Thanks a million @dejan . If you need support from more collaborators I am happy to help. I have been using Rails Panel for years now and I am big fan

**Comment by amrdruid** [comment]
@dejan Just a soft nudge on this one 😄

**Pull request merged**
