### PR TITLE
add cache tab, fix rendering of color logging

### PR DESCRIPTION
**Pull request by modosc**
1. add a tab for active_support cache instrumentation 
2. fix bug where html generated from `ansi2html` wouldn't be rendered - i tested this by logging html and something in color and the html remains escaped while the added colors are converted to html and rendered correctly.

### CODE REVIEW

**Comment by modosc** [comment]
also, happy to help with maintenance / releases if that would make things easier.

**Comment by dejan** [comment]
@modosc here, please do.

**Comment by modosc** [comment]
@dejan thanks! can you also add me to the chrome extension so i can push changes out there as well?

**Comment by dejan** [comment]
I don't think that's possible. I will publish the new releases, when you create them here.

**Comment by modosc** [comment]
i'm happy to just do merges / version bumps on github if you can still do the chrome store / rubygems releases. i'm also happy to assist with those too: 

https://developer.chrome.com/webstore/publish#set-up-group-publishing_1
http://guides.rubygems.org/command-reference/#gem-owner

tonight i'll get stuff merged / tested here so you can get it out. thanks again!

**Pull request merged**
